package com.example.yannam.as1;

import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;

import com.firebase.client.Firebase;


public class Root extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_root);
        Firebase.setAndroidContext(this);       //Initializing the Firebase Libraries
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.root, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();
        return id == R.id.action_settings || super.onOptionsItemSelected(item);
    }

    //                  **************************************
    // **********************CODE REFERENCE FROM FIREBASE********************** //
    //                          *********************


    // To read and write data from our Firebase, the below reference is made
    // to the URL generated by the Firebase into the Firebase constructor.
    // Creating a reference to read and write data to Firebase.
    Firebase myFirebaseRef = new Firebase("https://boiling-inferno-5847.firebaseio.com/");


}

